language: C++

install:
install: git clone --depth=50 --branch=master https://github.com/swxEmily/repo.git ../../swxEmily/repo && cd swxEmily/repo && git checkout
cd ../../ && ls -alF
cd swxEmily/porxy && ls -alF && g++ main.cc -o main