language:
    - python
     
python:
    - "3.5"


jobs:
    include:
        - stage: cpp test
          dist: xenial
          install: sudo apt-get install gcc-aarch64-linux-gnu
          env:
            matrix:
                - SHELL="aa"
                - SHELL="bb"
          script: echo $SHELL
          name: "presentor_ut"
        - script: echo "cc"
          name: "st"
