language: C++

install:
    - git clone --depth=50 --branch=master https://github.com/swxEmily/repo.git ../../swxEmily/repo
    - cd ../../swxEmily/repo && git checkout
    - cd ../../ && tree
    - cd swxEmily/proxy && ls -alF && g++ main.cc -o main